### ISSUE TITLE
BUG: page templates not available in v12 since 11.0.4

### ISSUE THREAD

**Issue by kraemer-igroup** [FluidTYPO3/flux#2259]
I recently updated our v12 instance to flux 11.0.4 (and also just tried 11.0.5).
The problem is, that the page templates are no longer available to select within the page properties and the sites config. (generic error: _An error occurred trying to process items for field "Page Layout - this page" (Tried resolving a template file for controller action "Page->default" in format ".html", but none of the paths contained the expected template file (Page/Default.html)._)

It seems that the following change to `‎Classes/Service/PageService.php` produces the error on our instance:
https://github.com/FluidTYPO3/flux/commit/36adfe46a6c5321a06a2aae2ae2cbeddd160d9af#diff-730b3be4a307b37d47de6b5b3ad6326336f52d7237780e594a8092cbe18637a9

Is there a specific configuration needed for this change to "work"? We used flux with many TYPO3 version and never had this issue with our current configuration.

Unfortunately I can not investigate this further at moment, but still wanted to create this report, maybe someone else has the same issue?

**Comment by lucmuller** [comment]
+1

**Comment by NamelessCoder** [comment]
I believe this is related to the recent deprecation fixes, which avoids constructing TemplateView and TemplatePaths instances directly since this operation triggers massive amounts of deprecation log messages.

**Comment by NamelessCoder** [comment]
I expect this is solved in the next Flux release. Sorry for the inconvenience!

**Comment by kraemer-igroup** [comment]
Thanks @NamelessCoder for looking so quick into this.

I just tested the new 11.0.6 release (and also the development branch) - the errors are gone, but it's not quite working like before:
before:
<img width="259" height="165" alt="Image" src="https://github.com/user-attachments/assets/d28a2ef1-b282-46f7-a0a3-e8da80cf4e11" />

after:
<img width="354" height="229" alt="Image" src="https://github.com/user-attachments/assets/92e94ab4-7eef-458a-b37d-d9957fb619d4" />

The labels are missing and there are additional templates available like `error` and `render`.
Do you have any idea what the reason for this could be?

**Comment by NamelessCoder** [comment]
This looks like a side effect of switching to the more unified View creation logic. The one solution I can think of right this minute is kind of a workaround - you can use the Site Configuration to limit which templates you integrate. It would also be great if you could create a dedicated Github issue about those unwanted templates, then I'll look into a more permanent solution to exclude those baked-in templates - they're essentially fallbacks for Flux to use when no other templates apply / errors happen in the "real" templates, but they're added to the collection due to template paths now also containing Flux's own paths.

**Comment by parzerphilipp** [comment]
In V13 this error still exists - somewhere (while creating the view) the Controller and Action Name get lost

**Comment by parzerphilipp** [comment]
While creating the view, the TemplatePathAndFilename gets lost:
PageService.php:255 -> add following line
`$templatePaths->setTemplatePathAndFilename($file->getPathname());`
