### ISSUE TITLE
Paste (copy/move), drag-n-drop and localisation bugs

### ISSUE THREAD

**Issue by NamelessCoder** [FluidTYPO3/flux#573]
This issue is the **single** place to report **any** type of issue of this type:

> "My record is incorrectly positioned, contains incorrect values or was not created as expected after performing a paste/drag-n-drop command or after creating a localised version of the original record"

If your bug fits this description, report it here!

If any bugs in the mentioned areas still exist **after May 28th 2014** please report them here instead of creating new issues. Before you report problems, make sure your Flux repository is checked out on the `development` branch and that you have pulled (or possibly reset) to obtain the latest changes.

### Currently known bugs in copying:

* [Issue with missing re-referencing FAL elements in a copy of a record](#issuecomment-44843860) **SOLVED** - most recent TYPO3 CMS core `master` branch plus most recent flux `development` branch has this bug solved.

#### Related core patches:

https://review.typo3.org/#/c/30633/ which ensures passing the field name while TYPO3 iterates over fields of a record. Without this patch, the logic which retrieves files stored in FlexForm references, may in some cases fail to detect the existence of said references, because Flux receives a NULL field name and thus may return an incorrect Form instance (read: resolves the Provider with highest priority for the table while ignoring the field name in priority verdict) which does not contain the correct definitions for the record field currently being processed. Furthermore, due to Flux tracking which Provider was called with a certain field, Flux was unable to execute any but the first Provider detected through this logic in TYPO3. Applying the patch passes the field name and Flux returns the correct data structure when TYPO3 iterates record fields to detect file references in FlexForm fields.

https://review.typo3.org/#/c/30632/ adds an error prevention for records which have FlexForm fields that contain references that were not correctly processed (due to the bug above). Install this patch only if you are being faced with an Exception when attempting to edit affected records.

### Currently known bugs in moving:

* "Move record up" using sorting arrows causes record to disappear when child content record is **second** in list.

![687474703a2f2f692e696d6775722e636f6d2f6d697659336d632e706e67](https://cloud.githubusercontent.com/assets/2228052/4264020/e8797578-3c10-11e4-8208-cad3b920d50d.png)

### Currently known bugs in drag and drop:

* After dropping a content element from one `colPos` to another and then *immediately thereafter* using the "insert content after" link associated with the content record that was moved, the created content element is created inside the *original* `colPos` value. The content object may become invisible in page editing mode - to retrieve, use the list view and set proper `colPos` and as needed, `Relations` values.

### Currently known bugs in localisation:

* [FCE childs with language property 'All' are still translated when translating parent using "copy all default elements" button](#issuecomment-44837888). **Rejected**, the TYPO3 core is responsible for this behavior, which happens when localising any type of 1:n or m:n record when children can be localised.

**Comment by glucka** [comment]
The localised (copied) elements have always the original colPos.
Copy a content element (which have localised versions) from Column (colPos = 0)
Paste into Column with colPos 1
After paste the copied localised content elements have always colPos = 0

**Comment by twirsing** [comment]
I am not sure how this is addressed above in  **"Translating an contentelement within an FCE is causing the newly localized element to have no relation to the fce. [..]"** but al least the behavior I experience is inconsistent.
Only when I use the "Synchronize with original language" feature in the parent content element within the second language a new child element of the original language is correctly created. But when I try to create an translation of an "child"-element from the original language using the top dropdown of the content element, the tx_flux_parent is not correctly set. All the other fields are handled correctly. So the new translation appears in the wrong language. I am using Typo3 6.2.9 and all the current versions of flux, fluidcontent, fluidpages and vhs. Both master and development branches show the same behavior.

**Comment by f000** [comment]
I'm using current master of flux, fluidpages and fluidcontent on TYPO3 6.2.9 w/o css_styled_content.

My content FCEs are nested in FCE Row and Rows are nested in FCE Section. For grids I'm using cols without colPos parametr `<flux:grid.column name="unique" />`.

**Bug 1:**
If I set grid FCE to Language: [All] and try to localize children using List module, in FE on localized page children gets displayed twice.

**Bug 2:**
Switch to Page module "Languages" view introduces additional area called "Fluid Content Area" with badly messed content. All elements are in wrong order and elements from 3rd level of nesting are displayed twice (separately + in 2nd level elements). At least, is it possible to hide this area?

**Bug 3:**
If I click "Copy default elements" in Page module "Languages" view "Fluid Content Area" I'm getting
*newlog()] Localization failed; Source record had another language than "Default" or "All" defined!*
and 2nd+3rd level nested FCEs gets physically duplicated in default language.

**Comment by fgerards** [comment]
We use FLux TER 7.1.2 and TYPO3 6.2.9 official core.
When copying FCEs with flux:field.inline.fal - relations, the count() value in the Flexform in the DB is replaced by a comma-separated list of the uid's of the pic-relations. 
Isn't this core/TCE-Bug already solved in 6.2.9 master ?
@NamelessCoder : Do you have any uptodate-status of this issue in the 6.2.9 core ?

**Comment by NamelessCoder** [comment]
@fgerards No, sorry - I don't know if that FAL-copy-reference issue is fixed in 6.2.9. If it isn't, you should definitely push for it today, since the code sprint is still in effect.

**Comment by Outdoorsman** [comment]
**Drag/drop as well as cut/paste are not working for me... the content element disappears.** This happens when I create a four column row in fluidbootstraptheme and then drag pre-exisiting content into one of the four columns I just create (nested content).

Also if I try to move content from column to column within the fluidbootstraptheme four column content element, it will either work, ignore my action completely, or reorder where it's at in that column. Some content element types seemed drag/drop better in this scenario than others... strange.

I'm using:
* TYPO3 6.2.10
* Development branches of all FluidTYPO3 extensions and fluidbootstraptheme.

**Comment by Outdoorsman** [comment]
I just upgraded to TYPO3 CMS 7.1.0 thinking that would help but **nested drag/drop is still not working** in either version of TYPO3 CMS.

**Comment by Outdoorsman** [comment]
Ahhhhhhhhhh!

**Comment by Outdoorsman** [comment]
Maybe I've just hijacked this issue but it seems that it's grown beyond the original issue already. Here's a specific example:

I'm experiencing issues with drag/drop of content between columns of the four column-wide grid FCE from fluidbootstraptheme.  Some things work, some don't.  Yesterday I was noticing that the Text and fluidbootstraptheme's  Simple Responsive Image content elements behaved differently when trying to drag/drop.

**Comment by CarstenD** [comment]
I'am currently having the same issue than @Outdoorsman

**Comment by CarstenD** [comment]
Bugfix: https://github.com/FluidTYPO3/flux/pull/798

**Comment by franzkugelmann** [comment]
i experience the same problem as twirsing commented on 24 Jan:
Translating an element within a fce (default language) does place the translated element still within the fce in default language instead of within the translated version of the fce.

Gridelements had the same issue, i currently use the same logic to update tx_flux_parent to the id of the localized container within an processDatamapClass hook, seems to work well:
https://forge.typo3.org/issues/50800
https://review.typo3.org/#/c/30509/1/Classes/DataHandler/PreProcessFieldArray.php

**Comment by DenisMir** [comment]
I am experiencing a copy & paste error with the following setup: 
flux@7.2.0, fluidpages@3.2.0, fluidcontent@4.2.1, vhs@2.3.2, typo3@6.2.12

Here is the workflow that allow me to reproduce the bug: 

* Create a fluidcontent wrapper element that contains a `<flux:form.content name="content" />` area
* Create another fluidcontent wrapper element inside the first one that contains two columns created with
```xml
      <flux:grid>
        <flux:grid.row>
          <flux:grid.column name="content.colOne" />
          <flux:grid.column name="content.colTwo" />
        </flux:grid.row>
      </flux:grid>
```
* Create a fluidcontent simple child element inside the `content.colOne`
* Copy the child element and paste it into `content.colTwo`
* The pasted element does not appear. If you switch to the list view it does appear but `tx_flux_parent` and `tx_flux_column` is empty

**Comment by BenjaminBeck** [comment]
Hi @DenisMir,
thanks for this list!
The fix for the last one of the bugs you encountered (1) has just been merged to development.
That commit should also fix your issues in the table from "Update 2".

**Comment by DenisMir** [comment]
@BenjaminBeck Great. I will update my developement branch and test out the fix.

**Comment by hkarvasonis** [comment]
Is "fluidcontent_core" extension required for those updates to work correctly?

**Comment by BenjaminBeck** [comment]
Hi hkarvasonis,
as i understand the copy & paste function should not depend on fluidcontent_core.
I uninstalled fluidcontent_core on my system and can confirm that without this extension pasting into fluidcontent areas is broken.

**Comment by mkoehler2911** [comment]
Found bugs (still existing)

###Bug 1:
- I create an element inside of my page container (flux:grid) of my default language
- localize this element with the "copy default elements"-button
	- Bug 1.1: if there are other elements on that page the localized element is (often) not at same position like the default langugage element
	- Bug 1.2: elements can't move by drag & drop in "language"-view only "column"-view
- I move my created element (default langugage) inside of an existing container (flux:grid, 1 column)
	- Bug 1.3: my localized element jumped to the top of my page (sometimes to the bottom)

######tt_content:	

default language element | localized element
------------ | -------------
tx_flux_column | tx_flux_column
content | 

default language element | localized element
------------ | -------------
tx_flux_parent | tx_flux_parent
5990 | 0

###Bug 2:
- I create an element inside of a flux:grid container (default language)
	- Bug 2.1: there's no "copy default elements"-button

###Bug 3:
- I create an element (example: fal image) inside of a flux:grid container (default language)
- I localize that element in list-view
	- Bug 3.1: the localized element is inside of my default language flux:grid container (below my first created element)

######tt_content:

default language element | localized element
------------ | -------------
tx_flux_parent | tx_flux_parent
19776 | 19776

###Bug 4:
- I create an element inside of my page container (flux:grid) of my default language
- localize this element with the "copy default elements"-button
	- Bug 4.1: if I move the default element the localized element won't move to the same position

**Comment by robsonrobi** [comment]
Is there any progress concerning that topic? We really looking forward for a solution.

Thanks.

**Comment by andreaswolf** [comment]
I fixed a few of the issues mentioned here on an older version about a year ago. I wrote functional tests for them, so its easy to find out when stuff breaks again. Unfortunately, on the current development version, my version of the class ContentService is totally broken. I’m currently investigating the matter, trying to find out which change outside ContentService broke the tests.

If you’re interested in my code, head to my fork here on Github: https://github.com/andreaswolf/flux/tree/working-content-service-tests

The mentioned test case is in https://github.com/andreaswolf/flux/blob/working-content-service-tests/Tests/Functional/Service/ContentServiceTest.php.

**Comment by xf-** [comment]
@andreaswolf thx
Maybe the best way would be, if we add tests in a WIP branch and resolve everything. Better a broken test as no tests at all. Target to close this issue.

What do you think?

**Comment by NamelessCoder** [comment]
Nevermind the tests, guys. I can fix those that break - if you focus on the behavior I'll do the tests afterwards.

**Comment by andreaswolf** [comment]
I cannot really focus on the behaviour, as I don’t know how it should work. I just created a testsuite according to my client’s descriptions of what broke for them, and fixed those issues one by one. The resulting tests and the reworked ContentService worked a year ago, but I cannot get the tests green after rebasing onto the current development branch. See my fork (branch development) for the version I’m currently working on.

**Comment by andreaswolf** [comment]
Ok, I found the reason why my tests break: The ContentProvider is not called anymore for regular content elements (at least in my test), as my content elements have a CType set, but there is none defined in the provider. Therefore, the check in trigger() fails.

I have no clue if this is because I use flux in a wrong way or if something is really broken. Glad for any hint into the right direction :-)

**Comment by NamelessCoder** [comment]
Hi Andreas,

ContentProvider should trigger on any record from `tt_content` when the field `pi_flexform` is included in the field list (see links below). Could this be the cause for your tests failing? If so, I should think you can simply set an empty string as `$record['pi_flexform']` on your database record test fixture.

https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/ContentProvider.php#L41 defines triggering table and field name.
https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/AbstractProvider.php#L197 shows the triggering method that checks table and field, among other things.

It is possible that the trigger method does something unexpected, but I'm hoping it is just because of the expected field name. If all else fails you can create a fixture Provider and register that, or mock the resolveConfigurationProvider* method(s), but I'm sure you know all this ;)

Please ping if I can assist with more info! Anything I can do to help.

**Comment by andreaswolf** [comment]
Hi Claus,

thanks for the pointer. Unfortunately, this did not fix the problem: I stepped through AbstractProvider::trigger() and the problem is that $contentObjectType is not set in ContentProvider. As my content records do have a content type already, the check $matchesContentType fails.

Apart from that, I would like to stay away from mocking as long as possible. These functional tests should test the actual default behaviour as I would expect it from Flux. If my tests do make false assumptions, these need to be fixed instead :-)

Additionally, I wonder why ContentService::pasteAfter is triggered by such an exclusive check. As far as I see, it makes sense to execute this method after every paste operation, right?

**Comment by NamelessCoder** [comment]
@coding46 you were picking at this issue a while back, right? Issues with the trigger() method on ContentProvider? What @andreaswolf notes here is actually correct and may be an edge case that happens on first saving the record; we may need to not only check explicitly if `$record['CType'] is NULL, but also if it is `empty()`. I'm not sure what TYPO3 posts in this case but I expect an empty string.

**Comment by andreaswolf** [comment]
No, CType contains (at least in my test cases) an actual value like "text". trigger() already checks if the configured value matches the one in the record or if both are empty. But both these checks are useless, as they won’t catch the general case that *all* records need to be processed after they were inserted. Or am I missing something?

**Comment by NamelessCoder** [comment]
I think what has happened here is that originally, we did not need to trigger any Provider unless the record we were operating on (via TCEMain/DataHandler) actually contained a Flux-enabled field. Earlier, the Provider was responsible mainly for things like trimming the Flux-enabled fields and analysing/removing inherited variables. And we had "pure" TCA relations as our way to support localising all children of a particular column and cascading deletions; etc.

But at some point we lost the ability to depend on the various parameters being passed from the page module to our code - there was a switch from using actual URL parameters to using XHR with harvested variables. And we were unable to affect these variables correctly in order to make the TYPO3 core itself cause all these things - for example, adding the parent content element UID and column name. Since then we have implemented numerous fixes, the most ugly of which is the use of large negative integers for `colPos` values, stored in a temporary session variable, so that our Provider can translate this large negative integer to a set of parent UID and column name. Bad, bad, bad. But the only way we had available.

At this point (sorry about the history lesson here but I think it's relevant or I wouldn't bother you) we began facing issues: non-Flux-enabled content elements *were not being correctly processed when for example we added new content in a Flux content column*. Putting two an two together it becomes quite obvious why we have these problems - it is, of course, since we *now depend on a Provider for every single content record even if the record has nothing to do with Flux*. We are in this situation because of the recent changes that switched from calling a URL to harvesting and doing an XHR.

It should be the solution to adapt ContentProvider in a way that it triggers (at least) once per content record regardless of anything configured in this record. The only trigger variable should be: "is this record from `tt_content`?". If it is, our ContentProvider needs to operate on it or relationships will fail because of all of the above history.

On a side note this *should* also mean that we can completely remove the [LightWeightProvider](https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/LightweightProvider.php). It seems to have been created to get around this issue but it only partially solves it, in that it only listens for a limited set of commands - where the ContentProvider would be listening to all commands as it should.

**Comment by NamelessCoder** [comment]
Hi Andreas,

Would you mind trying your functional tests on top of the linked pull request? I have adapted ContentProvider to make sure it triggers this once per `tt_content` record as mentioned and have discarded the LightweightProvider at the same time. It may not solve the issue but at least the code you're testing should then be executed.

**Comment by andreaswolf** [comment]
Claus, will do tomorrow. Thanks for taking care! :)

**Comment by Marc-Bauer** [comment]
Hi,
I have fixed the problem with moveing content elements in flux columns (see patch)
<pre>
Index: typo3conf/ext/flux/Classes/Service/ContentService.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- typo3conf/ext/flux/Classes/Service/ContentService.php	(revision 104)
+++ typo3conf/ext/flux/Classes/Service/ContentService.php	(revision )
@@ -13,6 +13,7 @@
 use TYPO3\CMS\Core\DataHandling\DataHandler;
 use TYPO3\CMS\Core\SingletonInterface;
 use TYPO3\CMS\Core\Utility\GeneralUtility;
+use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
 
 /**
  * Flux FlexForm integration Service
@@ -208,11 +209,15 @@
 			} elseif (0 <= (integer) $relativeTo && FALSE === empty($parameters[1])) {
 				list($prefix, $column, $prefix2, , , $relativePosition, $relativeUid, $area) = GeneralUtility::trimExplode('-', $parameters[1]);
 				$relativeUid = (integer) $relativeUid;
+				$relativePosition = 'top';
 				if ('colpos' === $prefix && 'page' === $prefix2) {
 					$row['colPos'] = $column;
 					if ('top' === $relativePosition && 0 < $relativeUid) {
 						$row['tx_flux_parent'] = $relativeUid;
 						$row['tx_flux_column'] = $area;
+						if($GLOBALS['BE_USER']->workspaceRec['uid'] != 0) {
+							$row['t3ver_wsid'] = $GLOBALS['BE_USER']->workspaceRec['uid'];
+						}
 					}
 				}
 			} elseif (0 > (integer) $relativeTo) {
Index: typo3conf/ext/flux/Classes/Provider/LightweightProvider.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- typo3conf/ext/flux/Classes/Provider/LightweightProvider.php	(revision 103)
+++ typo3conf/ext/flux/Classes/Provider/LightweightProvider.php	(revision )
@@ -11,6 +11,7 @@
 use FluidTYPO3\Flux\Service\ContentService;
 use TYPO3\CMS\Core\DataHandling\DataHandler;
 use TYPO3\CMS\Core\Utility\GeneralUtility;
+use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
 
 /**
  * LightweightProvider for moved records
@@ -52,6 +53,20 @@
 	 */
 	public function postProcessCommand($command, $id, array &$row, &$relativeTo, DataHandler $reference) {
 		$moveData = $this->getMoveData();
+//		DebuggerUtility::var_dump($moveData);
+		if(empty($moveData) === TRUE) {
+			$callback = $this->getCallbackCommand();
+			if (TRUE === isset($callback['paste'])) {
+				$pasteCommand = $callback['paste'];
+//				DebuggerUtility::var_dump($pasteCommand);
+				$parameters = explode('|', $pasteCommand);
+				$parameters[1] = 'colpos-18181-page-'.$parameters[1];
+				$moveData = $parameters;
+			}
+		}
+//		DebuggerUtility::var_dump($moveData);
+//		die();
+
 		$this->contentService->moveRecord($row, $relativeTo, $moveData, $reference);
 	}
 



</pre>

**Comment by xf-** [comment]
looks interesting, includes Workspaces :)
Do you want to create a Pull Request?

**Comment by Marc-Bauer** [comment]
yes of course if have done it. 
including a bug fix for copy content elements in flux content columns. :) Including Workspaces too ;)

**Comment by cgrossde** [comment]
I just tested copy and paste with the latest 6.2 version of Typo3 (branch: TYPO3_6-2) and Flux (branch: development). 

When I copy a standard text element I get the following error:

~~~
Uncaught TYPO3 Exception
#1257246929: "" is not a valid template resource URI. (More information)

TYPO3\CMS\Fluid\View\Exception\InvalidTemplateResourceException thrown in file
/var/www/html/typo3_src/typo3/sysext/fluid/Classes/View/TemplateView.php in line 338.

17 TYPO3\CMS\Fluid\View\TemplateView::getTemplateSource()

/var/www/html/typo3conf/ext/flux/Classes/View/ExposedTemplateView.php:
00134:    $parsedTemplate = $this->templateCompiler->get($templateIdentifier);
00135:   } else {
00136:    $source = $this->getTemplateSource();
00137:    $parsedTemplate = $this->templateParser->parse($source);
00138:    if (TRUE === $parsedTemplate->isCompilable()) {

16 FluidTYPO3\Flux\View\ExposedTemplateView::getParsedTemplate()

/var/www/html/typo3conf/ext/flux/Classes/View/ExposedTemplateView.php:
00109:   $this->baseRenderingContext->setControllerContext($this->controllerContext);
00110:   $this->templateParser->setConfiguration($this->buildParserConfiguration());
00111:   $parsedTemplate = $this->getParsedTemplate();
00112:   $this->startRendering(AbstractTemplateView::RENDERING_TEMPLATE, $parsedTemplate, $this->baseRenderingContext);
00113:   $viewHelperVariableContainer = $this->baseRenderingContext->getViewHelperVariableContainer();

15 FluidTYPO3\Flux\View\ExposedTemplateView::getStoredVariable("FluidTYPO3\Flux\ViewHelpers\FormViewHelper", "form", "Configuration")

/var/www/html/typo3conf/ext/flux/Classes/View/ExposedTemplateView.php:
00066:  public function getForm($sectionName = 'Configuration', $formName = 'form') {
00067:   /** @var Form $form */
00068:   $form = $this->getStoredVariable(AbstractFormViewHelper::SCOPE, $formName, $sectionName);
00069:   if (NULL !== $form && TRUE === isset($this->templatePathAndFilename)) {
00070:    $form->setOption(Form::OPTION_TEMPLATEFILE, $this->templatePathAndFilename);

14 FluidTYPO3\Flux\View\ExposedTemplateView::getForm("Configuration", "form")

/var/www/html/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php:
00288:      $viewContext->setVariables($variables);
00289:      $view = $this->configurationService->getPreparedExposedTemplateView($viewContext);
00290:      $form = $view->getForm($section, $formName);
00291:     }
00292:    }

13 FluidTYPO3\Flux\Provider\AbstractProvider::getForm(array)

/var/www/html/typo3conf/ext/flux/Classes/Provider/AbstractProvider.php:
00632:   */
00633:  public function postProcessDataStructure(array &$row, &$dataStructure, array $conf) {
00634:   $form = $this->getForm($row);
00635:   if (NULL !== $form) {
00636:    $dataStructure = $form->build();

12 FluidTYPO3\Flux\Provider\AbstractProvider::postProcessDataStructure(array, "No source value in fieldname "tx_templavoila_ds"", array)

/var/www/html/typo3conf/ext/flux/Classes/Backend/DynamicFlexForm.php:
00073:   $providers = $this->configurationService->resolveConfigurationProviders($table, $fieldName, $row);
00074:   foreach ($providers as $provider) {
00075:    $provider->postProcessDataStructure($row, $dataStructArray, $conf);
00076:   }
00077:  }

11 FluidTYPO3\Flux\Backend\DynamicFlexForm::getFlexFormDS_postProcessDS("No source value in fieldname "tx_templavoila_ds"", array, array, "tt_content", "")
~~~

**Comment by eckonator** [comment]
There is currently still a bug with multilingual sites. If I switch in backend to Modul "Web" -> "Page" -> Langauge-View and there creating 2 content elements and move one of them down, the translation goes to the fluid content area if i do there the same. Is it already known? I think there goes something terrible wrong and the backend runs in a memory limit error. After this, i cant revisit this page in backend and have to delete in directly in phpmyadmin. Tested with the current development branch at TYPO3 6.2 LTS.

![bug-transaltion-moving](https://cloud.githubusercontent.com/assets/13748683/9198424/4bcf2a20-403c-11e5-9465-7fa17b8ef632.png)

**Comment by robsonrobi** [comment]
The same problem exist in TYPO3 7.4 (https://github.com/FluidTYPO3/flux/issues/886)

**Comment by xf-** [comment]
Hi,
this issue and big reference list is closed.
Looks like a issue is in translation and position. Please use new issue crated by @robsonrobi #886
