### ISSUE TITLE
[ Flux 7.2.1 + Typo3 6.2.14 ] Moving FCEs in the Backend inside another FCE make them disappear ( FCE done with Flux or basic FCE of Typo3 )

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/flux#927]
Hi,

Ièm actually using the latest version of Flux 7.2.1 with Typo3 6.2.14 and I'm having a strange issue: when I try to move a content element ( Drag'n'Drop ) from one FCE to another FCE done with Flux the item is there graphically after you move it, but if you try to reload the page the item disappears and is no more attached to any column in the page.

This is the current template of the container when I'm doing the tests of moving out - moving in - moving from one column to the other.

All three cases make the item disappear when they're released inside any of the ContentRows.

Thank you in advance for any help.

P.S.: I'm using `deniedContentTypes` on purpose and maybe it's because of that if other items disappear but even moving allowed Content Types make them anyway disappearing.

```html
  <div xmlns="http://www.w3.org/1999/xhtml" lang="en"
  xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
  xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
  xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers">

  <f:layout name="Content" />

  <f:section name="Configuration">
    <flux:form id="bwccontentrow33-33-33" label="Content Row 33_33_33" options="{group: 'Container'}">
      <!-- Insert fields, sheets, grid, form section objects etc. here, in this flux:flexform tag -->
      <flux:grid>
        <flux:grid.row>
          <flux:grid.column name="ContentRows-0"  style="width: 33.33333333%" label="Row 1">
            <flux:form.variable name="Fluidcontent" value="{deniedContentTypes:'bwcon:MegaMenuItem.html,bwcon:MegaMenuSearchForm.html,bwcon:MegaMenuSimpleItem.html, bwcon:MegaMenuThreeColumnsContainer.html, bwcon:MegaMenuTwoColumnsContainer.html'}" />
          </flux:grid.column>
          <flux:grid.column name="ContentRows-1" style="width: 33.33333333%" label="Row 2">
            <flux:form.variable name="Fluidcontent" value="{deniedContentTypes:'bwcon:MegaMenuItem.html,bwcon:MegaMenuSearchForm.html,bwcon:MegaMenuSimpleItem.html, bwcon:MegaMenuThreeColumnsContainer.html, bwcon:MegaMenuTwoColumnsContainer.html'}" />
          </flux:grid.column>
          <flux:grid.column name="ContentRows-2" style="width: 33.33333333%" label="Row 3">
            <flux:form.variable name="Fluidcontent" value="{deniedContentTypes:'bwcon:MegaMenuItem.html,bwcon:MegaMenuSearchForm.html,bwcon:MegaMenuSimpleItem.html, bwcon:MegaMenuThreeColumnsContainer.html, bwcon:MegaMenuTwoColumnsContainer.html'}" />
          </flux:grid.column>
        </flux:grid.row>
      </flux:grid>
    </flux:form>
  </f:section>

  <f:section name="Preview">
    <h4 style="margin: 10px 0px 10px 0px ">Content Row 33_33_33</h4>
  </f:section>

  <f:section name="Main">
  <div class="row">
    <div class="col-md-4">
        <flux:content.render area="ContentRows-0" />
    </div>
    <div class="col-md-4">
        <flux:content.render area="ContentRows-1" />
    </div>
    <div class="col-md-4">
        <flux:content.render area="ContentRows-2" />
    </div>
    </div>
  </f:section>
</div>
```

**Comment by NamelessCoder** [comment]
Fixed in development branch of Flux, expected released to TER tomorrow (Sept. 20th). Unrelated to denied/allowedContentTypes.

**Comment by julianxhokaxhiu** [comment]
Can I ask which is the commit related to this fix?

Because I'm using the latest dev version up to [this commit](https://github.com/FluidTYPO3/flux/commit/73eac6aa58d2e9993a0e67a9c5fa2a2cb9fad700) and is still not working.

**Comment by NamelessCoder** [comment]
There's a list of related commits in the newly added changelog section - https://github.com/FluidTYPO3/flux/blob/development/CHANGELOG.md.

Note that:

* Your areas have invalid names using `-` which is likely to break the JS routine that extracts target area name - TYPO3 uses `-` as parameter separator in target area identifiers.
* You may need to manually flush all caches including system cache for the preview contents to be regenerated completely including any compiled templates.
