### ISSUE TITLE
Localisation support for fluidpages page configuration the second time

### ISSUE THREAD

**Issue by Shupal** [FluidTYPO3/flux#932]
Hey there,

i know the ticket https://github.com/FluidTYPO3/flux/issues/506 is closed but i have no clue how to create multi language page configurations with the lastest stable release. 

Is there any documentation or quickguide how to solve this? 

In the chatroom was the answer just to create a tca record and add it via the "old" way. Is this still the best option?

thanks in advance

**Comment by julianxhokaxhiu** [comment]
Up, same problem here. I dubugged the Fluid Translate View Helper and as the `extensionName` now I get `Fluidpages` and not my extension name. Should I do something special with version 7.2.2?

On 7.2.1 everything was fine. Thanks in advance.

**Comment by melaniemedialight** [comment]
Hello,

I have the same problem.

It seems that in the getPageValues() method the page variable is overwrite by the first page overlay value.
When a page overlay exists the values of the overlay replace the values of the default language page.
By commenting the arrays merging the problem is solved.

**Comment by Shupal** [comment]
@melaniemedialight do you have the page configuration tab in a second language?

**Comment by lsascha** [comment]
just noticed this entry. I created a quick fix here: https://github.com/FluidTYPO3/flux/issues/954
still missing a "deleted" check, but it works in my project for now. (just making sure there are no deleted page_overlays for a page)

**Comment by NamelessCoder** [comment]
Hi guys,

Please see:

* https://fluidtypo3.org/blog/news/flux-option-translation-and-typo3-76-lts.html
* https://github.com/FluidTYPO3/fluidpages/pull/296

#954 will be taken care of either as part of the pull request or shortly thereafter.

Cheers,
Claus
